name: flutter_qiita_client
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  dio: ^4.0.4
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_hooks: ^0.18.1
  freezed_annotation: ^1.0.0
  hooks_riverpod: ^1.0.2
  http: ^0.13.4
  json_annotation: ^4.4.0
  pretty_dio_logger: ^1.1.1
  retrofit: ^3.0.0
  visibility_detector: ^0.2.2

dev_dependencies:
  build_runner: ^2.1.5
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^1.0.2
  json_serializable: ^6.1.1
  mockito: ^5.0.16
  retrofit_generator: ^3.0.0+2

flutter:
  uses-material-design: true
  assets:
    - .env
